### ISSUE TITLE
RFC: Some proposed changes

### ISSUE THREAD

**Issue by FelipeEmos** [kuubson/react-vite-trpc#7]
Hi, I have some ideas for improving this repo and I'd like to know what you think.

Depending on your response I'd happily open a PR / some PRs addressing them.

### Server Hotreload
We can add a simple `nodemon` setup so that when you change some code in the server, it will automatically reload the changes that you made. This is a great DX.

### Basic Github Actions
I know every project has some peculiarities and since this is a template we shouldn't add too much, but having some small github actions in place can be very useful and, honestly, pretty easy to delete if you don't like them.
This amazing Template repo called [Create-T3-Turbo](https://github.com/t3-oss/create-t3-turbo) is a great reference of template repo in my opinion. They implemented some simple github actions and I could implement something very similar for this project.

What it does is: everytime you open a PR, Github automatically runs the ESLint checks in your changes to see if something went wrong with your types and code formatting. Great stuff!

### License
It is pretty nice to have a License file in the project so it's more obvious how people can use your repo. Projects usually go for is the MIT License, would you be up for that one? That is a very standard license that allows people to take your code to any direction they want... which is perfect for a template repo. That's the same license they are using in [Create-T3-Turbo](https://github.com/t3-oss/create-t3-turbo)

**Comment by kuubson** [comment]
Hi! That's a really great input and I appreciate it so much! 🤜🤛

I've been improving the **entire** setup recently and I've just merged a new [pull request](https://github.com/kuubson/react-vite-trpc/pull/8) that also addresses the concerns you raised.

Please don't hesitate to provide feedback if I've overlooked anything or if you come across additional matters.

If you have any other ideas, feel free to open PR and contribute 🚀
